version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps

    steps:
      - checkout
      - run: clojure -m kaocha.runner

workflows:
  version: 2
  test:
    jobs:
      - test
