name: "Tracker"

on:
  push:
    branches:
      - master

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.1.java11'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'
      - run: clojure -m kaocha.runner --reporter documentation
